title: Jitesh Kumar
description: Game Developer & Designer with 3+ years of experience
show_downloads: true
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
